spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/chronobidule
    username: postgres
    password: postgres
#  jpa:
#    show-sql: true
springdoc:
#  api-docs:
#    enabled: false
  swagger-ui:
    url: /openapi.yml