spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/chronobidule
    username: postgres
    password: postgres
#  jpa:
#    show-sql: true
#  resources:
#    static-locations: classpath:/static/
  thymeleaf:
    cache: false
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    url: /openapi.yml