services:
  db:
    container_name: chronobidule-db
    image: postgres:17.4-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: chronobidule
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 1s
      retries: 5
