server.port: 9090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/chronobidule-store
    username: postgres
    password: postgres

chronobidule.central.baseUrl: http://localhost:8080
